<a href="https://colab.research.google.com/github/silviyax03/Luxury-Housing-Sales-Analysis/blob/main/Luxury_Housing_Sales_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Data manipulation
import pandas as pd
import numpy as np

# Data visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Ignore warning messages
import warnings
warnings.filterwarnings("ignore")

In [ ]:
df = pd.read_csv("/content/Luxury_Housing_Bangalore.csv")

In [ ]:
df.head()

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.750846039118798,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292151871065954,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724412961911,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367494232896,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.345392444511946,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.

In [ ]:
# Display the number of rows and columns
df.shape

(101000, 18)

In [ ]:
# Display all column names
df.columns

Index(['Property_ID', 'Micro_Market', 'Project_Name', 'Developer_Name',
       'Unit_Size_Sqft', 'Configuration', 'Ticket_Price_Cr',
       'Transaction_Type', 'Buyer_Type', 'Purchase_Quarter',
       'Connectivity_Score', 'Amenity_Score', 'Possession_Status',
       'Sales_Channel', 'NRI_Buyer', 'Locality_Infra_Score',
       'Avg_Traffic_Time_Min', 'Buyer_Comments'],
      dtype='object')

In [ ]:
# Display dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101000 entries, 0 to 100999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           101000 non-null  object
 1   Micro_Market          101000 non-null  object
 2   Project_Name          101000 non-null  object
 3   Developer_Name        101000 non-null  object
 4   Unit_Size_Sqft        90954 non-null   float64
 5   Configuration         101000 non-null  object
 6   Ticket_Price_Cr       90981 non-null   object
 7   Transaction_Type      101000 non-null  object
 8   Buyer_Type            101000 non-null  object
 9   Purchase_Quarter      101000 non-null  object
 10  Connectivity_Score    101000 non-null  float64
 11  Amenity_Score         90910 non-null   float64
 12  Possession_Status     101000 non-null  object
 13  Sales_Channel         101000 non-null  object
 14  NRI_Buyer             101000 non-null  object
 15  Locality_Infra_Score  101000 non-null  float64
 16  Avg_Traffic_Time_Min  101000 non-null  int64
 17  Buyer_Comments        82713 non-null   object
dtypes: float64(4), int64(1), object(13)
memory usage: 13.9+ MB

In [ ]:
# Count missing values in each column
df.isnull().sum()

Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft          10046
Configuration               0
Ticket_Price_Cr         10019
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score           10090
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          18287
dtype: int64

In [ ]:
# Check duplicate rows
df.duplicated().sum()

np.int64(1000)

In [ ]:
# Check dataset shape before removing duplicates
print("Shape before removing duplicates:", df.shape)

# Remove duplicate rows
df = df.drop_duplicates()

# Check dataset shape after removing duplicates
print("Shape after removing duplicates:", df.shape)

Shape before removing duplicates: (101000, 18)
Shape after removing duplicates: (100000, 18)

In [ ]:
# Check duplicate rows
df.duplicated().sum()

np.int64(0)

In [ ]:
df["Ticket_Price_Cr"].head(10)

0    12.750846039118798
1    16.292151871065954
2    10.517724412961911
3     9.396367494232896
4    15.345392444511946
5              ₹9.82 Cr
6    10.896752354445224
7     9.357538943683888
8    12.299449409872416
9     9.193310278863123
Name: Ticket_Price_Cr, dtype: object

In [ ]:
# Remove ₹ and Cr, then convert to numeric
df["Ticket_Price_Cr"] = (
    df["Ticket_Price_Cr"]
    .astype(str)
    .str.replace("₹", "", regex=False)
    .str.replace("Cr", "", regex=False)
    .str.strip()
)

# Convert the column to numeric
df["Ticket_Price_Cr"] = pd.to_numeric(df["Ticket_Price_Cr"], errors="coerce")

In [ ]:
df["Ticket_Price_Cr"].head(10)

0    12.750846
1    16.292152
2    10.517724
3     9.396367
4    15.345392
5     9.820000
6    10.896752
7     9.357539
8    12.299449
9     9.193310
Name: Ticket_Price_Cr, dtype: float64

In [ ]:
df["Ticket_Price_Cr"].dtype

dtype('float64')

In [ ]:
df["Configuration"].head(10)

0     4bhk
1     3Bhk
2     4bhk
3     3BHK
4     4Bhk
5     4bhk
6    5BHK+
7     3BHK
8     3Bhk
9     4Bhk
Name: Configuration, dtype: object

In [ ]:
# Convert Configuration values to uppercase
df["Configuration"] = df["Configuration"].str.upper()

In [ ]:
df["Configuration"].value_counts()

Configuration
5BHK+    33536
3BHK     33377
4BHK     33087
Name: count, dtype: int64

In [ ]:
df["Configuration"].head(10)

0     4BHK
1     3BHK
2     4BHK
3     3BHK
4     4BHK
5     4BHK
6    5BHK+
7     3BHK
8     3BHK
9     4BHK
Name: Configuration, dtype: object

In [ ]:
df["Micro_Market"].value_counts()

Micro_Market
Jayanagar            2157
Bannerghatta Road    2148
mg road              2144
Jp Nagar             2143
bannerghatta road    2137
jp nagar             2136
sarjapur road        2135
indiranagar          2127
SARJAPUR ROAD        2125
domlur               2124
WHITEFIELD           2124
jayanagar            2119
Sarjapur Road        2113
JAYANAGAR            2103
bellary road         2101
Electronic City      2099
MG ROAD              2098
JP NAGAR             2094
hennur road          2091
yelahanka            2090
BANNERGHATTA ROAD    2089
Kanakapura Road      2088
kanakapura road      2088
Yelahanka            2087
Hebbal               2083
Indiranagar          2078
RAJAJINAGAR          2077
Whitefield           2073
whitefield           2071
Rajajinagar          2070
ELECTRONIC CITY      2070
BELLARY ROAD         2062
rajajinagar          2060
KANAKAPURA ROAD      2059
INDIRANAGAR          2058
Hennur Road          2057
KORAMANGALA          2052
Bellary Road         2052
HEBBAL               2049
DOMLUR               2049
electronic city      2043
Mg Road              2042
hebbal               2040
YELAHANKA            2036
Koramangala          2024
koramangala          2017
HENNUR ROAD          2010
Domlur               2008
Name: count, dtype: int64

In [ ]:
df["Micro_Market"] = (
    df["Micro_Market"]
    .str.strip()
    .str.title()
)

In [ ]:
df["Micro_Market"].value_counts()

Micro_Market
Jayanagar            6379
Bannerghatta Road    6374
Jp Nagar             6373
Sarjapur Road        6373
Mg Road              6284
Whitefield           6268
Indiranagar          6263
Kanakapura Road      6235
Bellary Road         6215
Yelahanka            6213
Electronic City      6212
Rajajinagar          6207
Domlur               6181
Hebbal               6172
Hennur Road          6158
Koramangala          6093
Name: count, dtype: int64

In [ ]:
df["Developer_Name"].value_counts()

Developer_Name
SNN Raj              9224
Prestige             9224
Brigade              9135
L&T Realty           9126
Godrej               9123
Total Environment    9116
Puravankara          9077
Embassy              9075
RMZ                  9009
Sobha                8958
Tata Housing         8933
Name: count, dtype: int64

In [ ]:
df["Developer_Name"] = df["Developer_Name"].str.strip()

In [ ]:
df["Project_Name"].value_counts()

Project_Name
Project_499    200
Project_0      200
Project_1      200
Project_2      200
Project_483    200
              ...
Project_8      200
Project_7      200
Project_6      200
Project_5      200
Project_4      200
Name: count, Length: 500, dtype: int64

In [ ]:
df["Transaction_Type"].value_counts()

Transaction_Type
Primary      50013
Secondary    49987
Name: count, dtype: int64

In [ ]:
df["Transaction_Type"] = df["Transaction_Type"].str.strip()

In [ ]:
df["Buyer_Type"].value_counts()

Buyer_Type
CXO                20127
NRI                20002
Startup Founder    19997
Other              19948
HNI                19926
Name: count, dtype: int64

In [ ]:
df["Buyer_Type"] = df["Buyer_Type"].str.strip()

In [ ]:
df["Purchase_Quarter"].value_counts()

Purchase_Quarter
2024-03-31    12635
2024-09-30    12573
2023-06-30    12541
2023-09-30    12491
2024-06-30    12479
2024-12-31    12466
2023-12-31    12412
2025-03-31    12403
Name: count, dtype: int64

In [ ]:
df["Possession_Status"].value_counts()

Possession_Status
Under construction    33410
Launch                33341
Ready to move         33249
Name: count, dtype: int64

In [ ]:
df["Possession_Status"] = df["Possession_Status"].str.strip()

In [ ]:
df["Sales_Channel"].value_counts()

Sales_Channel
Online      25169
Broker      25124
NRI Desk    25032
Direct      24675
Name: count, dtype: int64

In [ ]:
df["Sales_Channel"] = df["Sales_Channel"].str.strip()

In [ ]:
df["NRI_Buyer"].value_counts()

NRI_Buyer
no     50036
yes    49964
Name: count, dtype: int64

In [ ]:
# Standardize Yes/No values
df["NRI_Buyer"] = (
    df["NRI_Buyer"]
    .str.strip()
    .str.title()
)

In [ ]:
df["NRI_Buyer"].value_counts()

NRI_Buyer
No     50036
Yes    49964
Name: count, dtype: int64

In [ ]:
df[["Unit_Size_Sqft", "Ticket_Price_Cr", "Amenity_Score"]].describe()

       Unit_Size_Sqft  Ticket_Price_Cr  Amenity_Score
count    90043.000000     90087.000000   90000.000000
mean      5972.040170        12.719069       7.504185
std       1783.226054         7.670383       1.440567
min         -1.000000        -1.420000       5.000224
25%       4478.000000        10.010969       6.261394
50%       5990.000000        12.038456       7.499766
75%       7497.000000        14.097009       8.752300
max       8999.000000       100.000000       9.999865

In [ ]:
# Replace invalid values with NaN
df.loc[df["Unit_Size_Sqft"] <= 0, "Unit_Size_Sqft"] = np.nan
df.loc[df["Ticket_Price_Cr"] <= 0, "Ticket_Price_Cr"] = np.nan

In [ ]:
df[["Unit_Size_Sqft", "Ticket_Price_Cr"]].describe()

       Unit_Size_Sqft  Ticket_Price_Cr
count    89543.000000     90082.000000
mean      6005.393085        12.719806
std       1731.276595         7.669956
min       3000.000000         0.660000
25%       4504.000000        10.011617
50%       6004.000000        12.038619
75%       7505.000000        14.097041
max       8999.000000       100.000000

In [ ]:
# Fill missing values with median
df["Unit_Size_Sqft"].fillna(df["Unit_Size_Sqft"].median(), inplace=True)

df["Ticket_Price_Cr"].fillna(df["Ticket_Price_Cr"].median(), inplace=True)

df["Amenity_Score"].fillna(df["Amenity_Score"].median(), inplace=True)

In [ ]:
df["Buyer_Comments"].fillna("No Comments", inplace=True)

In [ ]:
# Count missing values in each column
df.isnull().sum()

Property_ID             0
Micro_Market            0
Project_Name            0
Developer_Name          0
Unit_Size_Sqft          0
Configuration           0
Ticket_Price_Cr         0
Transaction_Type        0
Buyer_Type              0
Purchase_Quarter        0
Connectivity_Score      0
Amenity_Score           0
Possession_Status       0
Sales_Channel           0
NRI_Buyer               0
Locality_Infra_Score    0
Avg_Traffic_Time_Min    0
Buyer_Comments          0
dtype: int64

In [ ]:
# Price per Sqft (in Crores per Sqft)
df["Price_per_Sqft"] = df["Ticket_Price_Cr"] / df["Unit_Size_Sqft"]

In [ ]:
df[["Ticket_Price_Cr","Unit_Size_Sqft","Price_per_Sqft"]].head()

   Ticket_Price_Cr  Unit_Size_Sqft  Price_per_Sqft
0        12.750846          4025.0        0.003168
1        16.292152          5760.0        0.002828
2        10.517724          7707.0        0.001365
3         9.396367          6192.0        0.001518
4        15.345392          7147.0        0.002147

In [ ]:
df["Purchase_Quarter"] = pd.to_datetime(df["Purchase_Quarter"])

In [ ]:
df["Quarter_Number"] = df["Purchase_Quarter"].dt.quarter

In [ ]:
df[["Purchase_Quarter","Quarter_Number"]].head()

  Purchase_Quarter  Quarter_Number
0       2025-03-31               1
1       2024-06-30               2
2       2023-12-31               4
3       2024-03-31               1
4       2024-12-31               4

In [ ]:
df["Purchase_Year"] = df["Purchase_Quarter"].dt.year
df["Quarter_Label"] = "Q" + df["Quarter_Number"].astype(str)

In [ ]:
df[["Purchase_Quarter","Quarter_Number","Purchase_Year","Quarter_Label"]].head()

  Purchase_Quarter  Quarter_Number  Purchase_Year Quarter_Label
0       2025-03-31               1           2025            Q1
1       2024-06-30               2           2024            Q2
2       2023-12-31               4           2023            Q4
3       2024-03-31               1           2024            Q1
4       2024-12-31               4           2024            Q4

In [ ]:
df.to_csv("Luxury_Housing_Cleaned.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [ ]:
from google.colab import files

files.download("Luxury_Housing_Cleaned.csv")

In [ ]:
df.head()

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,...,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments,Price_per_Sqft,Quarter_Number,Purchase_Year,Quarter_Label
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4BHK,12.750846,Primary,NRI,2025-03-31,...,Launch,Broker,Yes,9.212491,18,Loved the amenities!,0.003168,1,2025,Q1
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3BHK,16.292152,Primary,Other,2024-06-30,...,Under construction,NRI Desk,No,7.723898,106,No Comments,0.002828,2,2024,Q2
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4BHK,10.517724,Primary,HNI,2023-12-31,...,Ready to move,Direct,Yes,6.985493,113,Agent was not responsive.,0.001365,4,2023,Q4
3,PROP000004,Bellary Road,Project_3,Embassy,6192.0,3BHK,9.396367,Primary,HNI,2024-03-31,...,Ready to move,Online,Yes,6.100929,106,Excellent location!,0.001518,1,2024,Q1
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4BHK,15.345392,Secondary,HNI,2024-12-31,...,Under construction,Broker,No,5.312510,18,Too far from my office.,0.002147,4,2024,Q4